variables:
  REGISTRY: "registry-vpc.cn-shenzhen.aliyuncs.com/siss"

stages:
  - gitbook

before_script:
  - docker info

build:
  stage: gitbook
  script:
    - cd /data/gitbook && docker-compose down
    - rm -rf _book
    - docker rmi clarechu/git-book:1.0
    - gitbook build
    - docker build -t clarechu/git-book:1.0 .
    - cd /data/gitbook && docker-compose up -d
  tags:
    - shell