variables:
  REGISTRY: "registry-vpc.cn-shenzhen.aliyuncs.com/siss"

stages:
  - gitbook

before_script:
  - docker info

build:
  stage: gitbook
  script:
    - sh build.sh
    - cd /data/gitbook && docker-compose down
    - docker rmi clarechu/git-book:1.0
    - cd /data/gitbook && docker-compose up -d
  tags:
    - shell